spring.application.name=sistema-biblioteca
# Configuração do Servidor
server.port=8080

# Configuração do H2
spring.datasource.url=jdbc:h2:mem:bibliotecadb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Habilita o console do H2 para visualização
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Criação automática de tabelas (ideal para H2 em memória)
spring.jpa.hibernate.ddl-auto=update